### ISSUE TITLE
Waybar style

### ISSUE THREAD

**Issue by elythh** [anotherhadi/nixy#4]
Hello !
I love the aesthetic of your config. I wanted to try the Nixy theme for Waybar but i'm having weird results. I was wondering if you had any idea why.
![image](https://github.com/anotherhadi/nixy/assets/50964650/95a667f4-9e9c-40fc-9f9d-1f20f5c941f1)

1. The height
After debugging I found it was caused by the margin on the button but I'm unsure why it's so big.
2. The background
I'm unsure why I still have a background around the window module as well as a border around the workspaces buttons

I tried playing with the CSS but wasn't able to get the same result as you.

**Comment by elythh** [comment]
Nevermind i'm an idiot, I was still importing my old css at the same time.

**Comment by anotherhadi** [comment]
I'm glad that you like it!
Np 😁
