### ISSUE TITLE
workspace question

### ISSUE THREAD

**Issue by noahfraiture** [anotherhadi/nixy#6]
Hey,

I have a stupid question, I see that you have hyprpanel and hyprspace. But how does it works ? How do you have the workspace overview ?

**Comment by anotherhadi** [comment]
Hey! 
Hyprpanel is the bar on top of my screenshots, and hyperspace is an overview plug-in!
The workspace overview is toggled by SUPER+TAB or three-finger down on your trackpad.

**Comment by noahfraiture** [comment]
Great thank you
