### ISSUE TITLE
Hyprspace and hyprpanel

### ISSUE THREAD

**Issue by noahfraiture** [anotherhadi/nixy#7]
Hello,
I'm still making my configuration which is very similar to you, so I come here for question if you are willing to help me.
I have a problem : 
I can't configure hyprpanel to works correctly. If I try to add it into `home.packages = [ pkgs.hyprpanel ];`, I have an error saying it doesn't exists. I tried different way to add it in my flake.nix, but the documentation isn't very good. 
I tried to copy the related section in you flake.nix. Is there something I might be missing ? Something you did outside 
```              {
                nixpkgs.overlays = [ inputs.hyprpanel.overlay ];
                _module.args = {
                  inherit system;
                };
              }
``` 
and `hyprpanel.url = "github:Jas-SinghFSU/HyprPanel";`

I had it work a moment without putting it in home.packages and by calling `hyprpanel` instead of `pkgs.hyprpanel...` and removing hyprpanel from the home packages, but the configuration inside the cache wouldn't change if I change the theme with stylix, and thus the theme would stay the same always.

**Comment by anotherhadi** [comment]
Hello! The wiki for Hyprpanel changed recently, maybe give it another try?
I don't see where ur mistake is, you can try to ask in the hyprpanel discord server for help or open an issue in their repo! :)
