### ISSUE TITLE
Hyprpanel failing to build

### ISSUE THREAD

**Issue by gnussbaum1967** [anotherhadi/nixy#8]
Hi,

I get the following when running **sudo nixos-rebuild switch --flake ~/.config/nixos#nixos** (where nixos is my hostname)

`error: builder for '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv' failed with exit code 132;
       last 9 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/dxp36f7aj4cs8px5hjsv6iphcg9b8prb-kf3d107nnhk53vwl21k41ggy0ksgml5j-source
       > source root is kf3d107nnhk53vwl21k41ggy0ksgml5j-source
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/hilx2jwdslc05d38q4fzpsli6pgc56sa-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*"
       For full logs, run 'nix log /nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv'.
error: 1 dependencies of derivation '/nix/store/7c95isk973r9wzcbapvva4xv8n63x20q-hyprpanel.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8z9yy3ipjyvs2mxx0qyqa0pi9daxr6l9-hm_hyprhyprland.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3zfi2918z6av01pb01sb2ad7b55pmb2x-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v50frb739hhcfi2pm8r3i5ssydy9kdhd-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l0cgsk7q3i8kadk3f9sa3jqvnm5a3hjz-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f5my9m1myiylr7sarv5p12sr7sji2nwy-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6c85asx7ind986zghvyccxwrxk1wwz4y-nixos-system-nixos-24.11.20241029.807e915.drv' failed to build
`

I tried running a **sudo nix build -L '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv^*'** and got this:

`hyprpanel-latest> Running phase: unpackPhase
hyprpanel-latest> unpacking source archive /nix/store/dxp36f7aj4cs8px5hjsv6iphcg9b8prb-kf3d107nnhk53vwl21k41ggy0ksgml5j-source
hyprpanel-latest> source root is kf3d107nnhk53vwl21k41ggy0ksgml5j-source
hyprpanel-latest> Running phase: patchPhase
hyprpanel-latest> Running phase: updateAutotoolsGnuConfigScriptsPhase
hyprpanel-latest> Running phase: configurePhase
hyprpanel-latest> no configure script, doing nothing
hyprpanel-latest> Running phase: buildPhase
hyprpanel-latest> /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/hilx2jwdslc05d38q4fzpsli6pgc56sa-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*"
error: builder for '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv' failed with exit code 132
`

Any idea what may be causing this?  This is a NixOS vm on virtualbox.

**Comment by anotherhadi** [comment]
Hi, no idea! I don't have this issue on my barebones machine and never tried it in a VM.
Maybe open an issue in the hyprpanel repo

**Comment by simon-bueler** [comment]
@gnussbaum1967 I ran this config in a vm without issue. What are the specs of your vm?

**Comment by gnussbaum67** [comment]
> @gnussbaum1967 I ran this config in a vm without issue. What are the specs of your vm?

Hi,

Sorry for the late reply
VirtualBox
VM with 8GB RAM
2 CPU
100GB storage
3D acceleration enabled

**Comment by 0hDEADBEAF** [comment]
Hello, I have the same issue (tested on VirtualBox as well).

**Comment by gnussbaum1967** [comment]
> Hello, I have the same issue (tested on VirtualBox as well).

Hi,

I found that the CPU flags "AVX" and "AVX2" were missing.  Here's what I followed:

[https://stackoverflow.com/questions/65780506/how-to-enable-avx-avx2-in-virtualbox-6-1-16-with-ubuntu-20-04-64bit](url)
